var message = "Hello World";
console.log(message);
console.log("would you like to learn some python today?");
message = "abc";
console.log(message);
var firstName1 = "NAZIA";
var age = 23;
var isMarried = false;
var firstName = "2";
var firstName2 = 2;
var lastName = "22";
console.log(firstName1);
console.log(age);
console.log(isMarried);
console.log(firstName2);
console.log(lastName);
var num1 = 2;
var num2 = 5;
var result = num2 % num1;
console.log(result);
console.log(num2);
console.log(num1 + num2);
